### ISSUE TITLE
About "adversarial matching"

### ISSUE THREAD

**Issue by ShiYaya** [jimmy646/violin#3]
In your paper, you use adversarial matching to collect negative statements.
I want to know how do you calculate the similarity between two statements. Is similar model( ESIM+ELMo) and training strategy used in the VCR ?

**Comment by jimmy646** [comment]
We used a simpler approach, that is to take the average of embeddings of the words in a statement as its representation, and then use cosine to compute similarities.

**Comment by ShiYaya** [comment]
ok, thx
